apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}-backup
spec:
  schedule: {{ .Values.backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgresql-backup
            image: postgres:{{ .Values.image.tag }}
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-cluster.fullname" . }}
                  key: postgresql-password
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
            command:
            - /bin/sh
            - -c
            - >
              pg_dump -h {{ include "postgresql-cluster.fullname" . }} -U {{ .Values.postgresql.username }} {{ .Values.postgresql.database }} > /backups/backup-$(date +\%Y\%m\%d\%H\%M\%S).sql
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: {{ include "postgresql-cluster.fullname" . }}-backup-pvc


