---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
