apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}
type: Opaque
data:
  postgresql-username: {{ .Values.postgresql.username | b64enc }}
  postgresql-password: {{ .Values.postgresql.password | b64enc }}
