apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          default_type text/plain;
          return 200 "$server_addr\n";
          add_header server_ip $server_addr;
        }
      }
    }
